export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD"
export const REQUEST_SEARCHED_ANIME_PENDING = "FETCH_SEARCHED_ANIME_PENDING"
export const REQUEST_SEARCHED_ANIME_SUCCESS = "FETCH_SEARCHED_ANIME_SUCCESS"
export const REQUEST_SEARCHED_ANIME_FAILED = "FETCH_SEARCHED_ANIME_FAILED"
