export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD"
export const REQUEST_SEARCHED_ANIME_PENDING = "FETCH_SEARCHED_ANIME_PENDING"
export const REQUEST_SEARCHED_ANIME_SUCCESS = "FETCH_SEARCHED_ANIME_SUCCESS"
export const REQUEST_SEARCHED_ANIME_FAILED = "FETCH_SEARCHED_ANIME_FAILED"

export const REQUEST_CATEGORY_LINKS_PENDING = "REQUEST_CATEGORY_LINKS_PENDING"
export const REQUEST_CATEGORY_LINKS_SUCCESS = "REQUEST_CATEGORY_LINKS_SUCCESS"
export const REQUEST_CATEGORY_LINKS_FAILED = "REQUEST_CATEGORY_LINKS_FAILED"

export const REQUEST_CATEGORYS_PENDING = "REQUEST_CATEGORYS_PENDING"
export const REQUEST_CATEGORYS_SUCCESS = "REQUEST_CATEGORYS_SUCCESS"
export const REQUEST_CATEGORYS_FAILED = "REQUEST_CATEGORYS_FAILED"

export const REQUEST_RECOMMENDED_ANIME_PENDING =
  "REQUEST_RECOMMENDED_ANIME_PENDING"
export const REQUEST_RECOMMENDED_ANIME_SUCCESS =
  "REQUEST_RECOMMENDED_ANIME_SUCCESS"
export const REQUEST_RECOMMENDED_ANIME_FAILED =
  "REQUEST_RECOMMENDED_ANIME_FAILED"
